#!/usr/bin/env php
<?php
/*
 *  (c) Rogério Adriano da Silva <rogerioadris.silva@gmail.com>
 */
require_once __DIR__.'/vendor/autoload.php';
$app = require __DIR__.'/src/app.php';
$console = require __DIR__.'/src/console.php';
$console->run();
